-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Wed Apr 21 23:13:16 2021

-- parameterized module component declaration
component PLL_Clk
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_Clk
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
